version: '3'
services:
  centos7:
    image: centos:centos7.9.2009
    container_name: centos7
    restart: unless-stopped
    entrypoint: "sleep infinity"

  ubuntu:
    image: ubuntu:rolling
    container_name: ubuntu
    restart: unless-stopped
    entrypoint: "sleep infinity"