---
  el:
    hosts:
      centos7:
        vars:
          ansible_python_interpreter: /usr/bin/python
        ansible_connection: docker
  deb:
    hosts:
      ubuntu:
        vars:
          ansible_python_interpreter: /usr/bin/python3
        ansible_connection: docker
  local:
    hosts:
      localhost:
        ansible_connection: local
